name: Docker Publish

on:
  push:
    branches:
      - main
      - 'beta/*'
    tags:
      - v*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: model-service

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version information
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=$(git describe --tags --abbrev=0 --exclude="*-*" || echo "v0.0.0")
            VERSION=${VERSION#v}
            IFS='.' read -ra ADDR <<< "$VERSION"
            PATCH=$((ADDR[2] + 1))
            VERSION="${ADDR[0]}.${ADDR[1]}.$PATCH"
            if [[ "${GITHUB_REF}" == refs/heads/main ]]; then
              VERSION="$VERSION-latest"
            elif [[ "${GITHUB_REF}" == refs/heads/beta/* ]]; then
              VERSION="$VERSION-beta-$(date +%Y%m%d)"
            fi
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          IMAGE_ID=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo "Building Docker image with tag $IMAGE_ID:${{ env.VERSION }}"
          docker build . --file Dockerfile --tag $IMAGE_ID:${{ env.VERSION }} --label "runnumber=${GITHUB_RUN_ID}"
          docker push $IMAGE_ID:${{ env.VERSION }}

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: |
            ## Changes
            - Automated release of version ${{ github.ref }}
